name: Deploy HTML Pages

on:
  push:
    branches: [ main ]  # Cambia in 'master' se stai usando quel branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Il branch dove verrà pubblicato il sito
          folder: .         # La cartella che contiene i file HTML
          clean: true       # Pulisce i file esistenti nel branch gh-pages